### ISSUE TITLE
loading 40 controllers takes 40 seconds

### ISSUE THREAD

**Issue by ekmobile** [egodigital/express-controllers#1]
Loading a lot of controllers takes a long time. e.g. 40 controllers takes up to 40 seconds

Can it be possible to run the inclusion of the controller files in parallel?

e.g. with https://nodejs.org/api/worker_threads.html

**Comment by ekmobile** [comment]
https://nodejs.org/api/child_process.html

**Comment by ml-eds** [comment]
Didn't we check the issue and didn't we identify ts-node as the source of the problem? In production loading of controllers seems to be much faster.

I think this issue can be closed.
