### ISSUE TITLE
stopped working after updating to v.6.x.x 

### ISSUE THREAD

**Issue by ixLikro** [egodigital/express-controllers#2]
Hi there,
I've used these versions:
```
"@egodigital/egoose": "^3.6.0",
"@egodigital/express-controllers": "^5.4.0",
```
and the express-controllers worked perfectly. 👍
But I run into some issues with tsc. I noticed that my egoose version is incredibly old, so I updated it to the newest version, which solved the compiling error. But then the initControllers-Method crashed at startup, so I updated express-controllers to version 6.1.1.
Unfortunately this led to a different problem, my app is starting fine, but I can not access any controller. The server always returns ` Cannot GET {requestedPath}`

**Were there braking changes, did I miss a migration guide?**

My  initControllers-Method:
```
initControllers({
            app,
            cwd: __dirname + "/controllers",
            swagger:
                process.env.NODE_ENV !== "production"
                    ? {
                          definitions: swaggerDefinitions,
                          root: "/swagger",
                          document: {
                              basePath: "",
                              host: process.env.HOST_URL,
                              schemes: "http",
                              info: { title: "Driving-School-Manager" },
                              tags: getTagsAsObject(),
                          },
                      }
                    : false,
        });
```

**Comment by ml-eds** [comment]
I can confirm that 6.1.1 does not work with above configuration and initialization as described in README.md.

It seems that you have to explicitly add the "files" option with file-patterns of InitControllersOptions so that it will work again:

```
 ...
 app,
 cwd: __dirname + '/controllers',
 files: ['**/*.ts', '**/*.js'],
 ...
```

**Comment by mkloubert** [comment]
@ixLikro 

Moin, Ole!

Can you test the fix by Marc?

**Comment by ixLikro** [comment]
Moin,
thanks for the help!
Unfortunately, the fix does not help.
During the initController-Method I get now the following error:

```
backend_1  | /usr/src/app/api/node_modules/@egodigital/egoose/lib/index.js:283
backend_1  |     catch {
backend_1  |           ^
backend_1  | 
backend_1  | SyntaxError: Unexpected token {
backend_1  |     at createScript (vm.js:80:10)
backend_1  |     at Object.runInThisContext (vm.js:139:10)
backend_1  |     at Module._compile (module.js:617:28)
backend_1  |     at Object.Module._extensions..js (module.js:664:10)
backend_1  |     at Module.load (module.js:566:32)
backend_1  |     at tryModuleLoad (module.js:506:12)
backend_1  |     at Function.Module._load (module.js:498:3)
backend_1  |     at Module.require (module.js:597:17)
backend_1  |     at require (internal/module.js:11:18)
backend_1  |     at Object.<anonymous> (/usr/src/app/api/src/utility/helper.ts:2:1)
```

**Comment by mkloubert** [comment]
@ixLikro 

You seem to have an old Node version installed ... can you check this by executing "node -v"?

You require version 10 at least.

**Comment by ixLikro** [comment]
Yes, it was the node version! The local verion on my machine was 12.x.x but I used an old docker node image 🙈
With the image: `node:13-alpine` works everything smoothly 👍

Thank you very much!
As always, it's a pleasure to work with express-controllers 😍

Mit herzlichsten grüßen aus dem hohem Norden
Ole
