### ISSUE TITLE
Add information about Node version 10+ requirement?

### ISSUE THREAD

**Issue by ml-eds** [egodigital/express-controllers#4]
Perhaps it would be a good idea to document the Node 10+ requirement via "engines" in package.json and enforce it via .npmrc?

**package.json**

```
 "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
```

**.npmrc**

```
engine-strict=true
```

See 

[https://stackoverflow.com/a/50798589](https://stackoverflow.com/a/50798589)
[https://docs.npmjs.com/files/package.json#engines](https://docs.npmjs.com/files/package.json#engines)
[https://docs.npmjs.com/misc/config#engine-strict](https://docs.npmjs.com/misc/config#engine-strict)

Will this work? Any experience with this?

**Comment by mkloubert** [comment]
@ml-eds 

Great idea ... we also should do this with all the other of our own JavaScript / NPM projects with small PRs.
